# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N3OwdaA1No_8fPobaXQc7BmiyelkQvXA
"""

from keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
import numpy as np

!pip install wandb
import wandb

# Load the Fashion-MNIST dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()
wandb.login()
wandb.init(project="dl_assignment")

# Define the class names
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# Plot one sample image for each class
fig, axes = plt.subplots(1, 10, figsize=(10, 6))
axes = axes.ravel()
images=[]
for i in np.arange(0, 10):
    # Get the first image for each class
    idx = np.where(y_train == i)[0][0]
    img = x_train[idx]
    images.append(img)
    
    # Plot the image and set the title
    axes[i].imshow(img, cmap='gray')
    axes[i].set_title(class_names[i])
    axes[i].axis('off')
    dress_number = 0

for i in range(len(images)):
  plt.subplot(2,5,i+1)
  print(i+1)  
  plt.imshow(images[i]) 
  plt.title(class_names[i])
wandb.run.name="Question-1"
wandb.log({"Images":[wandb.Image(img,caption=item) for img,item in zip(images,class_names)]})
wandb.finish()


plt.show()